{"timestamp":"2025-10-28T22:00:01.507961","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-10-28T22:00:01.510139","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/Airflow.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-10-28T22:00:01.616665","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:01.621480","level":"info","event":"Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/scripts/DWD_ICON_EU.py']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:01.661701","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.383938","level":"info","event":"docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create\": dial unix /var/run/docker.sock: connect: permission denied.","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.384360","level":"info","event":"See 'docker run --help'.","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.389654","level":"info","event":"üîÑ Descargando datos de http://127.0.0.1:8081/v1/forecast ...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.390360","level":"info","event":"‚¨áÔ∏è Descargando temperature_2m del Bucket S3 de AWS...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.390667","level":"info","event":"Traceback (most recent call last):","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.390911","level":"info","event":"  File \"/opt/airflow/scripts/DWD_ICON_EU.py\", line 182, in <module>","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.391114","level":"info","event":"    main()","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.391430","level":"info","event":"  File \"/opt/airflow/scripts/DWD_ICON_EU.py\", line 162, in main","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.391669","level":"info","event":"    df, download_time = fetch_forecast(lats, lons)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.392058","level":"info","event":"                        ^^^^^^^^^^^^^^^^^^^^^^^^^^","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.392400","level":"info","event":"  File \"/opt/airflow/scripts/DWD_ICON_EU.py\", line 75, in fetch_forecast","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.392606","level":"info","event":"    subprocess.run([","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.392861","level":"info","event":"  File \"/usr/local/lib/python3.12/subprocess.py\", line 571, in run","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.393135","level":"info","event":"    raise CalledProcessError(retcode, process.args,","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.393508","level":"info","event":"subprocess.CalledProcessError: Command '['docker', 'run', '--rm', '-v', 'open-meteo-data:/app/data', 'ghcr.io/open-meteo/open-meteo', 'sync', 'dwd_icon_eu', 'temperature_2m']' returned non-zero exit status 126.","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-10-28T22:00:06.666345","level":"info","event":"Command exited with return code 1","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
